# Generated by Django 3.2 on 2022-05-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
