# Generated by Django 4.0.4 on 2022-05-16 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('c', 'Car'), ('m', 'Motorbike'), ('b', 'Bike')], max_length=1)),
                ('plate', models.CharField(max_length=6)),
                ('color', models.CharField(max_length=25)),
                ('engine', models.CharField(blank=True, choices=[('c', 'combustion'), ('e', 'electric')], max_length=1, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
