# Generated by Django 4.0.4 on 2022-05-16 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('aa651c5d-cf36-4eee-9f14-8037e989565f')),
        ),
    ]
