# Generated by Django 4.0.4 on 2022-05-16 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        ('place', '0003_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cb326474-ff60-49eb-b3e7-edfc42844c3f')),
        ),
        migrations.CreateModel(
            name='RackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.rack')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
